TWITTER_KEY: 'l97ud016YyKPxLiJq92gg'
TWITTER_SECRET: 'fmVQQrTJsEJIerb6KvC5I2ZPslBBWEDLExZ7ECmHQ'
OAUTH_TOKEN: '385667097-f8FZrEMS7Y1pN3s3L3pfWZwTldEqb7Y71KkSnJQ'
OAUTH_TOKEN_SECRET: 'KcnTFjbeVWFtYu6xAEbZJ7BlEdu0GCtM5kMbkLqtA'
